#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/wireops
  
  autopep8 -ai -r wireops
  autopep8 -ai *.py
  echo "not styling .git/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
