[meta]
version = "0.1.0"

[project]
name = "wireops"
package = "wireops"
main_lang = "py"
version = "0.2.8"
version_date = "2017-12-10"
author = "Jim Dixon"
author_email = "jdd@gmail.com"
description = "python3 protocol for compressed data transfer"
copyright = "2016-2017"
dev_status = "alpha"
license = "mit"
relpath = "py/wireops"
state = "shared"
url = "https://jddixon.github.io/wireops"

[py]
packages = [ "wireops",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib",]
requirements = [ "setuptools",]
test_requirements = []
